# Required: The name of your target APIM instance
apimServiceName: {API_MANAGEMENT_SERVICE_NAME}

# Override named values for production environment
namedValues:
  HWMBackendUrl: "https://api-prod.example.com/v1"
