openapi: 3.0.1
info:
  title: Hello World API
  description: "# Hello World API\n\nThis is a simple Hello World API that demonstrates the key features of OpenAPI 3.0.\n\n## Features demonstrated in this example\n- Multiple server environments (development, staging, production)\n- OAuth2 security definitions\n- Request and response examples\n- Comprehensive documentation\n- Schema definitions\n\n## Authentication\nThis API uses OAuth 2.0 for authentication. See the Security section for more details.\n"
  termsOfService: https://example.com/terms/
  contact:
    name: API Support Team
    url: https://example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: '1.0'
servers:
  - url: https://staging-apim-demo.azure-api.net/helloworld
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]