openapi: 3.0.1
info:
  title: Cat Facts API
  description: A simple API to get random cat facts
  contact:
    name: Alex Wohlbruck
    url: https://github.com/alexwohlbruck/cat-facts
  version: '1.0'
servers:
  - url: https://staging-apim-demo.azure-api.net/cat-facts
paths:
  /facts/random:
    get:
      summary: Get random facts
      description: Returns one or more random facts
      operationId: get-facts-random
      parameters:
        - name: animal_type
          in: query
          description: Type of animal the fact will describe
          schema:
            type: string
            default: cat
        - name: amount
          in: query
          description: 'Number of Facts to retrieve. If set to one, response will be a fact object. If many, response will be an array of Facts'
          schema:
            maximum: 500.0
            type: integer
            default: 1
      responses:
        '200':
          description: A fact object or an array of facts
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  __v:
                    type: integer
                  text:
                    type: string
                  updatedAt:
                    type: string
                    format: date-time
                  deleted:
                    type: boolean
                  source:
                    type: string
                  sentCount:
                    type: integer
              example:
                _id: string
                __v: 0
                text: string
                updatedAt: string
                deleted: true
                source: string
                sentCount: 0
        '400':
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
  '/facts/{factId}':
    get:
      summary: Get fact by ID
      description: Returns a specific fact by its ID
      operationId: get-facts-factid
      parameters:
        - name: factId
          in: path
          description: ID of the fact to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A fact object
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  __v:
                    type: integer
                  text:
                    type: string
                  updatedAt:
                    type: string
                    format: date-time
                  deleted:
                    type: boolean
                  source:
                    type: string
              example:
                _id: string
                __v: 0
                text: string
                updatedAt: string
                deleted: true
                source: string
        '404':
          description: Fact not found
          content:
            application/json: { }
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]